# Generated by Django 5.1.4 on 2026-05-18 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('pdf_file', models.FileField(upload_to='uploads/')),
                ('status', models.CharField(choices=[('uploaded', 'Загружен'), ('parsing', 'Парсинг PDF'), ('extracting', 'Извлечение требований'), ('scoring', 'Оценка рисков'), ('generating', 'Генерация предложения'), ('completed', 'Завершён'), ('failed', 'Ошибка')], default='uploaded', max_length=20)),
                ('progress_message', models.CharField(blank=True, max_length=200)),
                ('parsed_text', models.TextField(blank=True)),
                ('page_count', models.IntegerField(null=True)),
                ('summary', models.JSONField(blank=True, null=True)),
                ('risk_score', models.IntegerField(null=True)),
                ('risk_explanation', models.TextField(blank=True)),
                ('pitfalls', models.JSONField(blank=True, null=True)),
                ('technical_proposal', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('qualification', 'Квалификация'), ('technical', 'Технические'), ('financial', 'Финансовые'), ('deadline', 'Сроки'), ('document', 'Документы')], max_length=20)),
                ('status', models.CharField(choices=[('needs_review', 'Требует проверки'), ('critical', 'Критично'), ('warning', 'Предупреждение'), ('ok', 'Соответствует')], default='needs_review', max_length=20)),
                ('details', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='tenders.tender')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
