# Generated by Django 5.1.4 on 2026-05-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0002_alter_tender_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='contacts',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
